# This is a basic workflow to help you get started with Actions

name: test run processor

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - run: |
          set -x -e 
          echo sh: $0
          mkdir -pv pages 
          ls -ld data pages . 
          id
          
      - name: Resolve UID and GID
        run: 
         echo "UID=$( id -u ):$( id -g )" >> $GITHUB_ENV

      - name: Generate pages
        uses: addnab/docker-run-action@v3
        with:
          image: andriyg/pages-processor:0.0.8
          options: -v ${{ github.workspace }}:/pages --user=${{ env.UID }}   
          run: |
            set -x -e 
            ls -ld data pages . 
            id 
            java -jar /pages-processor.jar

      - name: Commit pages
        shell: bash
        run: |
          set -x -e 
          echo sh: $0
          cd pages 
          git add . 
          git status --porcelain -z | \
            cut -c 4- -z | \
            xargs --null git commit -m "static media sync" || { if [[ "$?" -ne 123 ]] ; then false ; fi } 


    
